alias Terp.Parser
alias Terp.AST
alias Terp.Arithmetic
alias Terp.Boolean
alias Terp.Function
alias Terp.IO
alias Terp.Evaluate
alias Terp.TypeSystem
alias Terp.TypeSystem.Type
alias Terp.TypeSystem.Evaluator
alias Terp.TypeSystem.Environment
